name: Guardian
version: 1.0.0
api: 5.0.0
main: veroxcode\Guardian
author: VeroxCode

commands:
  guardian:
    description: Guardian Commands
    permission: guardian.admin
    usage: /<guardian> help

permissions:
  guardian.admin:
    description: Admin Permissions
    default: op